name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:

    # Install Node
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Setup key
    - run: set -eu
    - run: mkdir "$HOME/.ssh"
    - run: echo "${{ secrets.key }}" > "$HOME/.ssh/key"
    - run: chmod 600 "$HOME/.ssh/key"

    # Build
    - run: npm run build

    # Deploy
    - run: cd dist && rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . pepelsbey@pepelsbey.dev:/var/www/pepelsbey.dev/html/
