name: EditorConfig

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  EditorConfig:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:

    # Install Node
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Run
    - name: Check EditorConfig
      run: npm run editorconfig
